name: clear-other-runs
on:
  issue_comment:
    types: [created, edited]

jobs:
  kindling:

    runs-on: ubuntu-18.04

    steps:
      - name: listen for PR comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/spark"
        env:
          GITHUB_TOKEN: ${{ secrets.XMAS_PARTY }}
        id: kindling

      - name: Event familiarization
        run: |
          echo "---steps.kindling.outputs.COMMENTER_USERNAME---"
          echo ${{ steps.kindling.outputs.COMMENTER_USERNAME }}

          echo "---steps.kindling.outputs.SHA---"
          echo ${{ steps.kindling.outputs.SHA }}

          echo "---steps.kindling.outputs.BOOL_TRIGGERED---"
          echo ${{ steps.kindling.outputs.BOOL_TRIGGERED }}
