name: respond-to-pr
on:
  pull_request:
    branches:
      - main
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  do-respond-to-pr:
    if: |
      contains(github.event.pull_request.labels.*.name, 'Talkie') &&
      github.event.pull_request.head.user.login != 'github-actions[bot]' &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.state == 'open'

    runs-on: ubuntu-18.04

    steps:
      - name: Respond to PR
        uses: actions/github-script@v5
        env:
          BRANCH: "${{ github.event.pull_request.head.ref }}"
        with:
          script: |
            console.log("reached");
            // read text from template file
            const fs = require("fs").promises;
            const msg = await fs.readFile("./github/helpers/tech_review_instructions.md", "utf8");
            console.log("read file")

            // format message with user and PR info
            const util = require("util");
            //const injected_msg = util.format(message, context.payload.issue.user.login, process.env.BRANCH, process.env.BRANCH, context.payload.repository);
            // username, branch, branch, repo
            console.log("formatted message")

            // create the comment?
            //github.rest.issues.createComment({
              //issue_number: context.issue.number,
              //owner: context.repo.owner, // as in account that owns the repo
              //repo: context.repo.repo,
              //body: injected_msg
            //});

